### ISSUE TITLE
sbt run - UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by gustawdaniel** [vmunier/play-scalajs.g8#60]
I cloned your porject and tried to run this. I obtained error:

    sbt run

```
Getting org.scala-sbt sbt 0.13.16  (this may take some time)...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.16!sbt.jar (6908ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.16/jars/main.jar ...
	[SUCCESSFUL ] org.scala-sbt#main;0.13.16!main.jar (2959ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.16/jars/compiler-interface.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar (4920ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.16/jars/actions.jar ...
	[SUCCESSFUL ] org.scala-sbt#actions;0.13.16!actions.jar (5783ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar ...
	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.16!main-settings.jar (4832ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.16/jars/interface.jar ...
	[SUCCESSFUL ] org.scala-sbt#interface;0.13.16!interface.jar (8987ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.16/jars/io.jar ...
	[SUCCESSFUL ] org.scala-sbt#io;0.13.16!io.jar (5981ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.16/jars/ivy.jar ...
	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.16!ivy.jar (8051ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.16/jars/logging.jar ...
	[SUCCESSFUL ] org.scala-sbt#logging;0.13.16!logging.jar (4753ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.16/jars/logic.jar ...
	[SUCCESSFUL ] org.scala-sbt#logic;0.13.16!logic.jar (5632ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.16/jars/process.jar ...
	[SUCCESSFUL ] org.scala-sbt#process;0.13.16!process.jar (5729ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.16/jars/run.jar ...
	[SUCCESSFUL ] org.scala-sbt#run;0.13.16!run.jar (11335ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/jars/command.jar ...
	[SUCCESSFUL ] org.scala-sbt#command;0.13.16!command.jar (3882ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar (275ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.16/jars/classpath.jar ...
	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.16!classpath.jar (5635ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.16/jars/completion.jar ...
	[SUCCESSFUL ] org.scala-sbt#completion;0.13.16!completion.jar (6887ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.16/jars/api.jar ...
	[SUCCESSFUL ] org.scala-sbt#api;0.13.16!api.jar (11100ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.16/jars/compiler-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar (5795ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar (11263ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/jars/relation.jar ...
	[SUCCESSFUL ] org.scala-sbt#relation;0.13.16!relation.jar (4652ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/jars/task-system.jar ...
	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.16!task-system.jar (12036ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.16/jars/tasks.jar ...
	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.16!tasks.jar (10019ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.16/jars/tracking.jar ...
	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.16!tracking.jar (6060ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.16/jars/testing.jar ...
	[SUCCESSFUL ] org.scala-sbt#testing;0.13.16!testing.jar (6743ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.16/jars/control.jar ...
	[SUCCESSFUL ] org.scala-sbt#control;0.13.16!control.jar (11252ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar ...
	[SUCCESSFUL ] org.scala-sbt#collections;0.13.16!collections.jar (2776ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
	[SUCCESSFUL ] jline#jline;2.14.4!jline.jar (341ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar ...
	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.16!classfile.jar (9968ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.16/jars/incremental-compiler.jar ...
	[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar (7000ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.16/jars/compile.jar ...
	[SUCCESSFUL ] org.scala-sbt#compile;0.13.16!compile.jar (4725ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar ...
	[SUCCESSFUL ] org.scala-sbt#persist;0.13.16!persist.jar (7808ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.16/jars/cross.jar ...
	[SUCCESSFUL ] org.scala-sbt#cross;0.13.16!cross.jar (4669ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar ...
	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4!ivy.jar (723ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
	[SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar (230ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.16/jars/cache.jar ...
	[SUCCESSFUL ] org.scala-sbt#cache;0.13.16!cache.jar (9945ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.16/jars/test-agent.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.16!test-agent.jar (4785ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar ...
	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar (9949ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (273ms)
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	49 artifacts copied, 0 already retrieved (17616kB/63ms)
[info] Loading project definition from /home/daniel/exp/play-scalajs.g8/project
[info] Updating {file:/home/daniel/exp/play-scalajs.g8/project/}play-scalajs-g8-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8/scala_2.10/sbt_0.13/0.10.0/jars/sbt-giter8.jar ...
[info] 	[SUCCESSFUL ] org.foundweekends.giter8#sbt-giter8;0.10.0!sbt-giter8.jar (6054ms)
[info] downloading https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-lib_2.10/0.10.0/giter8-lib_2.10-0.10.0.jar ...
[info] 	[SUCCESSFUL ] org.foundweekends.giter8#giter8-lib_2.10;0.10.0!giter8-lib_2.10.jar (439ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-plugin/0.13.16/jars/scripted-plugin.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#scripted-plugin;0.13.16!scripted-plugin.jar (4677ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/scalasti_2.10/2.1.2/scalasti_2.10-2.1.2.jar ...
[info] 	[SUCCESSFUL ] org.clapper#scalasti_2.10;2.1.2!scalasti_2.10.jar (168ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.pgm/3.7.0.201502260915-r/org.eclipse.jgit.pgm-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.pgm;3.7.0.201502260915-r!org.eclipse.jgit.pgm.jar (179ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/2.7.1/plexus-archiver-2.7.1.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-archiver;2.7.1!plexus-archiver.jar (176ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/grizzled-scala_2.10/3.1.0/grizzled-scala_2.10-3.1.0.jar ...
[info] 	[SUCCESSFUL ] org.clapper#grizzled-scala_2.10;3.1.0!grizzled-scala_2.10.jar (237ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/classutil_2.10/1.1.0/classutil_2.10-1.1.0.jar ...
[info] 	[SUCCESSFUL ] org.clapper#classutil_2.10;1.1.0!classutil_2.10.jar (156ms)
[info] downloading https://repo1.maven.org/maven2/org/antlr/ST4/4.0.8/ST4-4.0.8.jar ...
[info] 	[SUCCESSFUL ] org.antlr#ST4;4.0.8!ST4.jar (173ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm/5.1/asm-5.1.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm;5.1!asm.jar (157ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-commons;5.1!asm-commons.jar (149ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-util/5.1/asm-util-5.1.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-util;5.1!asm-util.jar (152ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-tree;5.1!asm-tree.jar (145ms)
[info] downloading https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar ...
[info] 	[SUCCESSFUL ] org.antlr#antlr-runtime;3.5.2!antlr-runtime.jar (168ms)
[info] downloading https://repo1.maven.org/maven2/args4j/args4j/2.0.12/args4j-2.0.12.jar ...
[info] 	[SUCCESSFUL ] args4j#args4j;2.0.12!args4j.jar (143ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.6/commons-compress-1.6.jar ...
[info] 	[SUCCESSFUL ] org.apache.commons#commons-compress;1.6!commons-compress.jar (179ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.archive/3.7.0.201502260915-r/org.eclipse.jgit.archive-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.archive;3.7.0.201502260915-r!org.eclipse.jgit.archive.jar (159ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/3.7.0.201502260915-r/org.eclipse.jgit-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit;3.7.0.201502260915-r!org.eclipse.jgit.jar (378ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.ui/3.7.0.201502260915-r/org.eclipse.jgit.ui-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.ui;3.7.0.201502260915-r!org.eclipse.jgit.ui.jar (142ms)
[info] downloading https://repo1.maven.org/maven2/org/tukaani/xz/1.4/xz-1.4.jar ...
[info] 	[SUCCESSFUL ] org.tukaani#xz;1.4!xz.jar (155ms)
[info] downloading https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.jar ...
[info] 	[SUCCESSFUL ] org.osgi#org.osgi.core;4.3.1!org.osgi.core.jar (177ms)
[info] downloading https://repo1.maven.org/maven2/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar ...
[info] 	[SUCCESSFUL ] com.googlecode.javaewah#JavaEWAH;0.7.9!JavaEWAH.jar(bundle) (153ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.1.3!httpclient.jar (177ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.2!slf4j-api.jar (158ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.1.4!httpcore.jar (161ms)
[info] downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ...
[info] 	[SUCCESSFUL ] commons-logging#commons-logging;1.1.1!commons-logging.jar (150ms)
[info] downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
[info] 	[SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (144ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-container-default;1.0-alpha-9-stable-1!plexus-container-default.jar (158ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.18/plexus-utils-3.0.18.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-utils;3.0.18!plexus-utils.jar (189ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/2.2/plexus-io-2.2.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-io;2.2!plexus-io.jar (158ms)
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.18 is selected over 1.0.4
[warn] 	    +- org.codehaus.plexus:plexus-archiver:2.7.1          (depends on 1.0.4)
[warn] 	    +- org.codehaus.plexus:plexus-io:2.2                  (depends on 1.0.4)
[warn] 	    +- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (depends on 1.0.4)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to play-scalajs.g8 (in build file:/home/daniel/exp/play-scalajs.g8/)
[info] Updating {file:/home/daniel/exp/play-scalajs.g8/}play-scalajs-g8...
[info] Resolving org.scala-sbt#scripted-sbt;0.13.16 ...
[warn] 	module not found: org.scala-sbt#scripted-sbt;0.13.16
[warn] ==== local: tried
[warn]   /home/daniel/.ivy2/local/org.scala-sbt/scripted-sbt/0.13.16/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt/0.13.16/scripted-sbt-0.13.16.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/daniel/.sbt/preloaded/org.scala-sbt/scripted-sbt/0.13.16/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/daniel/.sbt/preloaded/org/scala-sbt/scripted-sbt/0.13.16/scripted-sbt-0.13.16.pom
[info] Resolving org.scala-sbt#sbt-launch;0.13.16 ...
[warn] 	module not found: org.scala-sbt#sbt-launch;0.13.16
[warn] ==== local: tried
[warn]   /home/daniel/.ivy2/local/org.scala-sbt/sbt-launch/0.13.16/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/0.13.16/sbt-launch-0.13.16.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/daniel/.sbt/preloaded/org.scala-sbt/sbt-launch/0.13.16/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/daniel/.sbt/preloaded/org/scala-sbt/sbt-launch/0.13.16/sbt-launch-0.13.16.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-sbt#scripted-sbt;0.13.16: not found
[warn] 	:: org.scala-sbt#sbt-launch;0.13.16: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-sbt:scripted-sbt:0.13.16 ((sbt.ScriptedPlugin) ScriptedPlugin.scala#L104)
[warn] 		  +- default:play-scalajs-g8_2.10:0.1-SNAPSHOT
[warn] 		org.scala-sbt:sbt-launch:0.13.16 ((sbt.ScriptedPlugin) ScriptedPlugin.scala#L104)
[warn] 		  +- default:play-scalajs-g8_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scala-sbt#scripted-sbt;0.13.16: not found
unresolved dependency: org.scala-sbt#sbt-launch;0.13.16: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1541)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1537)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1572)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1570)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1575)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1569)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1592)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1519)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1471)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-sbt#scripted-sbt;0.13.16: not found
[error] unresolved dependency: org.scala-sbt#sbt-launch;0.13.16: not found
[error] Total time: 0 s, completed 2018-03-22 11:40:53
```

Additional info

```
Ubuntu 16.04
javac 1.8.0_161
sbt version 0.13.16
```

How to solve this?

**Comment by vmunier** [comment]
Hello,
The typesafe resolver was actually missing from the build. Thanks for pointing our this issue.
I have pushed this commit https://github.com/vmunier/play-scalajs.g8/commit/1ca7891e7ed0739f8c93724847feb41b594af7e9, which should fix it. So, you can pull the changes or clone a fresh copy of the repository and run `sbt` again.
PS: I first could not see this problem because the SBT dependency was already stored in my local cache.

**Comment by gustawdaniel** [comment]
Thank you. Now i ended with 

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.18 is selected over 1.0.4
[warn] 	    +- org.codehaus.plexus:plexus-archiver:2.7.1          (depends on 1.0.4)
[warn] 	    +- org.codehaus.plexus:plexus-io:2.2                  (depends on 1.0.4)
[warn] 	    +- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (depends on 1.0.4)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to play-scalajs.g8 (in build file:/home/daniel/exp/play-scalajs.g8/)
[info] Updating {file:/home/daniel/exp/play-scalajs.g8/}play-scalajs-g8...
[info] Resolving org.scala-sbt#sbt-launch;0.13.17 ...
[info] downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt/0.13.17/jars/scripted-sbt.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#scripted-sbt;0.13.17!scripted-sbt.jar (1955ms)
[info] downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-framework/0.13.17/jars/scripted-framework.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#scripted-framework;0.13.17!scripted-framework.jar (1844ms)
[info] downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/jars/sbt-launch.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#sbt-launch;0.13.17!sbt-launch.jar (3631ms)
[info] Done updating.
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 13 s, completed 2018-03-22 16:21:45
```

But I do not know java or scala well so maybe this is not the problem of this package, but just something wrong with my computer. I do not want to bother you. Issue to close.

**Comment by vmunier** [comment]
This project is only the Giter8 *template* to create an application (you cannot `sbt run` the template).
If you want to run the application that this Giter8 template produces, follow these steps:
```
$ sbt new vmunier/play-scalajs.g8 --name=play-scalajs --organization=com.example
$ cd play-scalajs
$ sbt
> run
$ open http://localhost:9000
```

**Comment by gustawdaniel** [comment]
Wow. Now it works! Thank you very much!
